//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection_Table
    {
        public int ID { get; set; }
        public string WhoSend { get; set; }
        public string mail { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string Date { get; set; }
    }
}
