//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginValidation_Table
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string PassWord { get; set; }
    }
}
